version: '3'

services:
  my_app:
    build: .
    ports:
      - "30025:3000"  # Map host port 8000 to container port 8000
    volumes:
      - .:/app  # Mount the current directory to /app inside the container